# Generated by Django 4.2.7 on 2026-06-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralRequest',
        ),
    ]
