# Generated by Django 4.2.7 on 2026-06-30 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('work_email', models.EmailField(max_length=254, unique=True)),
                ('domain_tags', models.JSONField(default=list, help_text="List of skill/domain keywords, e.g. ['Python', 'Backend', 'Django']")),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_token', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('referrals_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='referrals.employeeprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='referral_resumes/')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('', 'Not Submitted Yet'), ('submitted', 'Submitted to HR'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('hired', 'Hired 🎉'), ('rejected', 'Rejected')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_received', to='referrals.employeeprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_request', 'New Referral Request'), ('accepted', 'Request Accepted'), ('declined', 'Request Declined'), ('stage_update', 'Stage Updated')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_notifications', to=settings.AUTH_USER_MODEL)),
                ('referral_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='referrals.referralrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(help_text='e.g. google.com', max_length=255)),
                ('invite_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('referral_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='referrals.referralrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
