# Generated by Django 4.2.7 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
