# Generated by Django 4.2.7 on 2026-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysishistory',
            name='detailed_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
