# Generated by Django 4.2.7 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_resumeanalysishistory_detailed_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='credits_remaining',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
